Base Site Functionality
playwilmington/playwilmington.org pull request #15
Opened 2017-04-22 13:18 UTC by techgurupezza

2017-04-23 20:59 UTC, npezza93 commented on app/models/testimonial.rb
> +  scope :visable, -> { where(status: "Approved") }
spelled wrong

2017-04-23 21:00 UTC, npezza93 commented on app/models/slider.rb
> +  scope :visable, -> { where(active: true).order(:order) }
spelled wrong

2017-04-23 21:00 UTC, npezza93 commented on app/models/setting.rb
> +    return unless instagram_handle
instagram_handle.present?

2017-04-23 21:01 UTC, npezza93 commented on app/models/page.rb
> +    return unless page_type == "Page" && (icon.nil? || icon == "")
(icon.nil? || icon == "")  => icon.blank?

2017-04-23 21:01 UTC, npezza93 commented on app/models/page.rb
> +  scope :pages_tabs, -> { all.order(:order) }
just .order(:order)

2017-04-23 21:04 UTC, npezza93 requested changes
Seems decent. Couple tweaks. What's your code coverage sitting at?

2017-04-23 21:05 UTC, npezza93 commented
Got it 96%.

2017-04-23 21:09 UTC, techgurupezza commented on app/models/slider.rb
> +  scope :visable, -> { where(active: true).order(:order) }
whats spelled wrong?

2017-04-23 21:09 UTC, techgurupezza commented on app/models/testimonial.rb
> +  scope :visable, -> { where(status: "Approved") }
whats spelled wrong?

2017-05-19 23:50 UTC, npezza93 approved these changes

2017-05-19 23:55 UTC, merged